# 2019년

In [1]:
import pandas as pd
import numpy as np
import os
import re

os.chdir("D:/종합")
df1 = pd.read_excel("강정동 2019.xlsx")
df2 = pd.read_excel("건입동 2019.xlsx")
df3 = pd.read_excel("구좌 2019.xlsx")
df4 = pd.read_excel("남원읍 2019.xlsx")
df5 = pd.read_excel("대정읍 2019.xlsx")
df6 = pd.read_excel("색달동 2019.xlsx")
df7 = pd.read_excel("서귀동 2019.xlsx")
df8 = pd.read_excel("서호동 2019.xlsx")
df9 = pd.read_excel("성산 2019.xlsx")
df10 = pd.read_excel("아라동 2019.xlsx")
df11 = pd.read_excel("오등동 2019.xlsx")
df12 = pd.read_excel("외도일동 2019.xlsx")
df13 = pd.read_excel("용담 2019.xlsx")
df14 = pd.read_excel("우도 2019.xlsx")
df15 = pd.read_excel("월정 2019.xlsx")
df16 = pd.read_excel("표선읍 2019.xlsx")
df17 = pd.read_excel("한림읍 2019.xlsx")

## 2019년 바람

In [2]:
wind2017 = df1.loc[:"월.일",:"최대순간풍향"]
wind2017.rename(columns={"최대순간풍향":"강정동"}, inplace=True)
wind2017["건입동"] = df2["최대순간풍향"]
wind2017["구좌"] = df3[["최대순간풍향"]]
wind2017["남원읍"] = df4[["최대순간풍향"]]
wind2017["대정읍"] = df5[["최대순간풍향"]]
wind2017["색달동"] = df6[["최대순간풍향"]]
wind2017["서귀동"] = df7[["최대순간풍향"]]
wind2017["서호동"] = df8[["최대순간풍향"]]
wind2017["성산"] = df9[["최대순간풍향"]]
wind2017["아라동"] = df10[["최대순간풍향"]]
wind2017["오등동"] = df11[["최대순간풍향"]]
wind2017["외도일동"] = df12[["최대순간풍향"]]
wind2017["용담"] = df13[["최대순간풍향"]]
wind2017["우도"] = df14[["최대순간풍향"]]
wind2017["월정"] = df15[["최대순간풍향"]]
wind2017["표선읍"] = df16[["최대순간풍향"]]
wind2017["한림읍"] = df17[["최대순간풍향"]]

In [3]:
wind2017

,월.일,강정동,건입동,구좌,남원읍,대정읍,색달동,서귀동,서호동,성산,아라동,오등동,외도일동,용담,우도,월정,표선읍,한림읍
0,2019-01-01,315.0 / NW,315.0 / NW,305.8 / NW,5.7 / N,335.4 / NNW,311.9 / NW,282.7 / WNW,282.7 / WNW,282.7 / WNW,282.7 / WNW,315.0 / NW,315.0 / NW,340.0 / NNW,289.8 / WNW,337.6 / NNW,309.4 / NW,9.4 / N
1,2019-01-02,22.5 / NNE,22.5 / NNE,325.8 / NW,350.7 / N,323.9 / NW,349.1 / N,331.7 / NNW,331.7 / NNW,331.7 / NNW,331.7 / NNW,317.8 / NW,22.5 / NNE,40.0 / NE,287.4 / WNW,343.7 / NNW,320.6 / NW,9.6 / N
2,2019-01-03,14.1 / NNE,14.1 / NNE,341.1 / NNW,9.3 / N,95.5 / E,338.3 / NNW,329.7 / NNW,329.7 / NNW,329.7 / NNW,329.7 / NNW,295.3 / WNW,14.1 / NNE,50.0 / NE,289.7 / WNW,335.6 / NNW,317.8 / NW,48.1 / NE
3,2019-01-04,30.9 / NNE,30.9 / NNE,320.3 / NW,351.8 / N,240.3 / WSW,323.0 / NW,170.9 / S,170.9 / S,170.9 / S,170.9 / S,135.0 / SE,30.9 / NNE,40.0 / NE,298.3 / WNW,346.7 / NNW,320.6 / NW,24.1 / NNE
4,2019-01-05,0.0 / N,0.0 / N,295.9 / WNW,181.3 / S,356.6 / N,329.9 / NNW,326.8 / NNW,326.8 / NNW,326.8 / NNW,326.8 / NNW,292.5 / WNW,0.0 / N,40.0 / NE,294.4 / WNW,216.6 / SW,317.8 / NW,24.7 / NNE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,2019-12-27,292.5 / WNW,292.5 / WNW,325.6 / NW,360.0 / N,328.2 / NNW,319.7 / NW,330.4 / NNW,330.4 / NNW,330.4 / NNW,330.4 / NNW,320.6 / NW,292.5 / WNW,360.0 / N,295.5 / WNW,332.2 / NNW,306.6 / NW,6.3 / N
361,2019-12-28,303.8 / NW,303.8 / NW,335.2 / NNW,360.0 / N,135.6 / SE,21.3 / NNE,159.0 / SSE,159.0 / SSE,159.0 / SSE,159.0 / SSE,33.8 / NE,303.8 / NW,140.0 / SE,321.9 / NW,78.9 / E,33.8 / NE,13.7 / NNE
362,2019-12-29,275.6 / W,275.6 / W,137.4 / SE,238.2 / WSW,200.0 / SSW,248.7 / WSW,167.1 / SSE,167.1 / SSE,167.1 / SSE,167.1 / SSE,101.3 / ESE,275.6 / W,240.0 / WSW,113.3 / ESE,306.0 / NW,227.8 / SW,163.8 / SSE
363,2019-12-30,295.3 / WNW,295.3 / WNW,320.1 / NW,294.3 / WNW,326.7 / NNW,327.7 / NNW,280.5 / W,280.5 / W,280.5 / W,280.5 / W,315.0 / NW,295.3 / WNW,360.0 / N,291.4 / WNW,334.3 / NNW,315.0 / NW,61.1 / ENE
364,2019-12-31,309.4 / NW,309.4 / NW,310.9 / NW,354.4 / N,329.6 / NNW,311.4 / NW,319.7 / NW,319.7 / NW,319.7 / NW,319.7 / NW,337.5 / NNW,309.4 / NW,360.0 / N,288.0 / WNW,343.8 / NNW,340.3 / NNW,17.1 / NNE

In [4]:
wind2017.to_excel("wind2019.xlsx")

# 2019 최저기온

In [5]:
cold2017 = df1.loc[:"월.일",:"최저기온"]
cold2017.rename(columns={"최저기온":"강정동"}, inplace=True)
cold2017["건입동"] = df2[["최저기온"]]
cold2017["구좌"] = df3[["최저기온"]]
cold2017["남원읍"] = df4[["최저기온"]]
cold2017["대정읍"] = df5[["최저기온"]]
cold2017["색달동"] = df6[["최저기온"]]
cold2017["서귀동"] = df7[["최저기온"]]
cold2017["서호동"] = df8[["최저기온"]]
cold2017["성산"] = df9[["최저기온"]]
cold2017["아라동"] = df10[["최저기온"]]
cold2017["오등동"] = df11[["최저기온"]]
cold2017["외도일동"] = df12[["최저기온"]]
cold2017["용담"] = df13[["최저기온"]]
cold2017["우도"] = df14[["최저기온"]]
cold2017["월정"] = df15[["최저기온"]]
cold2017["표선읍"] = df16[["최저기온"]]
cold2017["한림읍"] = df17[["최저기온"]]

In [6]:
del cold2017["최대순간풍향"]
cold2017

,월.일,강정동,건입동,구좌,남원읍,대정읍,색달동,서귀동,서호동,성산,아라동,오등동,외도일동,용담,우도,월정,표선읍,한림읍
0,2019-01-01,4.8,4.8,3.9,4.1,4.1,3.8,0.4,0.4,0.4,0.4,2.3,4.8,4.5,4.1,4.9,3.1,4.4
1,2019-01-02,4.5,4.5,3.6,3.6,4.1,3.4,-0.1,-0.1,-0.1,-0.1,1.7,4.5,4.2,3.8,4.7,1.8,4.2
2,2019-01-03,3.5,3.5,1.2,-0.1,3.7,3.2,-2.3,-2.3,-2.3,-2.3,-0.6,3.5,2.8,3.6,2.3,1.0,3.0
3,2019-01-04,2.6,2.6,0.7,0,1.9,3.6,-3.3,-3.3,-3.3,-3.3,-1.2,2.6,1.7,5.4,1.9,1.7,1.7
4,2019-01-05,5.2,5.2,4.4,6.7,3.4,4.1,-0.6,-0.6,-0.6,-0.6,0.4,5.2,3.9,6.0,6.4,4.1,4.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,2019-12-27,5.7,5.7,5.4,5.3,4.7,4.7,1.4,1.4,1.4,1.4,3.1,5.7,5.7,5.7,6.7,3.8,5.3
361,2019-12-28,6.1,6.1,2.0,3.8,3.5,3.8,1.1,1.1,1.1,1.1,1.2,6.1,5.2,6.1,3.8,-1.0,4.4
362,2019-12-29,7.1,7.1,3.6,6.5,8.2,7.1,4.8,4.8,4.8,4.8,3.8,7.1,5.0,8.5,5.3,3.6,5.0
363,2019-12-30,6.3,6.3,6.1,7.4,5.7,5.5,2.4,2.4,2.4,2.4,3.8,6.3,6.0,6.4,7.3,5.5,5.8
364,2019-12-31,1.8,1.8,0.8,1.6,1.3,0.7,-2.2,-2.2,-2.2,-2.2,-0.8,1.8,1.5,1.2,2.2,-0.1,1.4

In [7]:
cold2017.to_excel("cold2019.xlsx")

# 2019 최고기온

In [8]:
hot2017 = df1.loc[:"월.일",:"최고기온"]
hot2017.rename(columns={"최고기온":"강정동"}, inplace=True)
hot2017["건입동"] = df2[["최고기온"]]
hot2017["구좌"] = df3[["최고기온"]]
hot2017["남원읍"] = df4[["최고기온"]]
hot2017["대정읍"] = df5[["최고기온"]]
hot2017["색달동"] = df6[["최고기온"]]
hot2017["서귀동"] = df7[["최고기온"]]
hot2017["서호동"] = df8[["최고기온"]]
hot2017["성산"] = df9[["최고기온"]]
hot2017["아라동"] = df10[["최고기온"]]
hot2017["오등동"] = df11[["최고기온"]]
hot2017["외도일동"] = df12[["최고기온"]]
hot2017["용담"] = df13[["최고기온"]]
hot2017["우도"] = df14[["최고기온"]]
hot2017["월정"] = df15[["최고기온"]]
hot2017["표선읍"] = df16[["최고기온"]]
hot2017["한림읍"] = df17[["최고기온"]]

In [9]:
del hot2017["최대순간풍향"]
del hot2017["최저기온"]
hot2017

,월.일,강정동,건입동,구좌,남원읍,대정읍,색달동,서귀동,서호동,성산,아라동,오등동,외도일동,용담,우도,월정,표선읍,한림읍
0,2019-01-01,7.0,7.0,5.8,8.7,7.2,8.0,2.3,2.3,2.3,2.3,4.3,7.0,6.4,6.1,7.0,7.7,7.2
1,2019-01-02,6.1,6.1,6.0,8.1,6.9,7.9,2.1,2.1,2.1,2.1,3.6,6.1,5.6,6.6,6.9,6.8,5.7
2,2019-01-03,8.0,8.0,7.3,12.4,8.2,10.6,4.4,4.4,4.4,4.4,5.2,8.0,6.7,7.6,8.0,8.1,7.1
3,2019-01-04,10.0,10.0,10.8,12.8,10.5,11.9,6.5,6.5,6.5,6.5,8.0,10.0,9.8,10.5,10.6,10.7,10.5
4,2019-01-05,9.0,9.0,8.3,10.8,9.6,12.9,6.2,6.2,6.2,6.2,6.6,9.0,8.2,8.8,8.9,9.2,8.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,2019-12-27,7.3,7.3,6.7,8.8,7.0,7.9,3.1,3.1,3.1,3.1,4.5,7.3,6.9,7.3,8.1,6.8,7.0
361,2019-12-28,9.6,9.6,9.2,11.8,11.8,11.2,6.6,6.6,6.6,6.6,7.5,9.6,8.9,9.5,9.7,10.0,10.2
362,2019-12-29,16.4,16.4,15.4,17.6,17.3,17.1,12.8,12.8,12.8,12.8,14.8,16.4,16.3,15.6,14.8,16.2,15.5
363,2019-12-30,13.6,13.6,13.6,17.3,13.7,15.5,11.2,11.2,11.2,11.2,12.8,13.6,13.4,14.1,14.6,14.2,13.2
364,2019-12-31,6.4,6.4,6.3,8.3,5.7,5.7,2.4,2.4,2.4,2.4,3.7,6.4,6.1,6.7,7.4,5.5,5.9

In [10]:
hot2017.to_excel("hot2019.xlsx")

# 2019 강우량

In [11]:
rain2017 = df1.loc[:"월.일",:"일강우량"]
rain2017.rename(columns={"일강우량":"강정동"}, inplace=True)
rain2017["건입동"] = df2[["일강우량"]]
rain2017["구좌"] = df3[["일강우량"]]
rain2017["남원읍"] = df4[["일강우량"]]
rain2017["대정읍"] = df5[["일강우량"]]
rain2017["색달동"] = df6[["일강우량"]]
rain2017["서귀동"] = df7[["일강우량"]]
rain2017["서호동"] = df8[["일강우량"]]
rain2017["성산"] = df9[["일강우량"]]
rain2017["아라동"] = df10[["일강우량"]]
rain2017["오등동"] = df11[["일강우량"]]
rain2017["외도일동"] = df12[["일강우량"]]
rain2017["용담"] = df13[["일강우량"]]
rain2017["우도"] = df14[["일강우량"]]
rain2017["월정"] = df15[["일강우량"]]
rain2017["표선읍"] = df16[["일강우량"]]
rain2017["한림읍"] = df17[["일강우량"]]

In [12]:
del rain2017["최대순간풍향"]
del rain2017["최저기온"]
del rain2017['최고기온']
rain2017

,월.일,강정동,건입동,구좌,남원읍,대정읍,색달동,서귀동,서호동,성산,아라동,오등동,외도일동,용담,우도,월정,표선읍,한림읍
0,2019-01-01,0.0,0.0,0.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.5,0.0,0.0,0.0
1,2019-01-02,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2019-01-03,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2019-01-04,1.6,1.6,0.0,1.5,0.5,1.5,2.0,2.0,2.0,2.0,2.0,1.6,2.0,0.0,0.0,0.5,1.0
4,2019-01-05,0.0,0.0,0.0,1.0,0.5,1.0,3.0,3.0,3.0,3.0,2.0,0.0,0.0,0.0,0.0,0.5,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,2019-12-27,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
361,2019-12-28,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
362,2019-12-29,11.4,11.4,24.0,30.0,19.0,25.0,NaN,NaN,NaN,NaN,14.5,11.4,10.5,33.0,15.0,32.5,18.0
363,2019-12-30,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
364,2019-12-31,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [13]:
rain2017.to_excel("rain2019.xlsx")

In [10]:
# =wind2017.loc[:,"강정동":"한림읍"]
# reg = "+"