# 2017년

In [58]:
import pandas as pd
import os
import re

os.chdir("D:/종합")
df1 = pd.read_excel("강정동 2017.xlsx")
df2 = pd.read_excel("건입동 2017.xlsx")
df3 = pd.read_excel("구좌 2017.xlsx")
df4 = pd.read_excel("남원읍 2017.xlsx")
df5 = pd.read_excel("대정읍 2017.xlsx")
df6 = pd.read_excel("색달동 2017.xlsx")
df7 = pd.read_excel("서귀동 2017.xlsx")
df8 = pd.read_excel("서호동 2017.xlsx")
df9 = pd.read_excel("성산 2017.xlsx")
df10 = pd.read_excel("아라동 2017.xlsx")
df11 = pd.read_excel("오등동 2017.xlsx")
df12 = pd.read_excel("외도일동 2017.xlsx")
df13 = pd.read_excel("용담 2017.xlsx")
df14 = pd.read_excel("우도 2017.xlsx")
df15 = pd.read_excel("월정 2017.xlsx")
df16 = pd.read_excel("표선읍 2017.xlsx")
df17 = pd.read_excel("한림읍 2017.xlsx")

## 2017년 바람

In [59]:
wind2017 = df1.loc[:"월.일",:"최대순간풍향"]
wind2017.rename(columns={"최대순간풍향":"강정동"}, inplace=True)
wind2017["건입동"] = df2["최대순간풍향"]
wind2017["구좌"] = df3[["최대순간풍향"]]
wind2017["남원읍"] = df4[["최대순간풍향"]]
wind2017["대정읍"] = df5[["최대순간풍향"]]
wind2017["색달동"] = df6[["최대순간풍향"]]
wind2017["서귀동"] = df7[["최대순간풍향"]]
wind2017["서호동"] = df8[["최대순간풍향"]]
wind2017["성산"] = df9[["최대순간풍향"]]
wind2017["아라동"] = df10[["최대순간풍향"]]
wind2017["오등동"] = df11[["최대순간풍향"]]
wind2017["외도일동"] = df12[["최대순간풍향"]]
wind2017["용담"] = df13[["최대순간풍향"]]
wind2017["우도"] = df14[["최대순간풍향"]]
wind2017["월정"] = df15[["최대순간풍향"]]
wind2017["표선읍"] = df16[["최대순간풍향"]]
wind2017["한림읍"] = df17[["최대순간풍향"]]

In [60]:
# res = wind2017["강정동"].str.extract('[\d]+\.\d')
wind2017.to_excel("wind2017.xlsx")

In [61]:
wind2017

,월.일,강정동,건입동,구좌,남원읍,대정읍,색달동,서귀동,서호동,성산,아라동,오등동,외도일동,용담,우도,월정,표선읍,한림읍
0,2017-01-01,163.1 / SSE,45.0 / NE,325.6 / NW,353.1 / N,143.7 / SE,20.5 / NNE,19.3 / NNE,19.3 / NNE,19.3 / NNE,19.3 / NNE,143.4 / SE,163.1 / SSE,80.0 / E,316.1 / NW,293.1 / WNW,185.6 / S,37.6 / NE
1,2017-01-02,115.3 / ESE,317.8 / NW,312.5 / NW,3.0 / N,243.3 / WSW,330.2 / NNW,173.1 / S,173.1 / S,173.1 / S,173.1 / S,165.9 / SSE,115.3 / ESE,180.0 / S,328.2 / NNW,299.9 / WNW,337.5 / NNW,22.0 / NNE
2,2017-01-03,135.0 / SE,298.1 / WNW,312.0 / NW,188.0 / S,345.8 / NNW,329.1 / NNW,314.6 / NW,314.6 / NW,314.6 / NW,314.6 / NW,171.6 / S,135.0 / SE,320.0 / NW,317.6 / NW,288.7 / WNW,326.3 / NNW,35.9 / NE
3,2017-01-04,112.5 / ESE,39.4 / NE,301.3 / WNW,342.8 / NNW,63.6 / ENE,142.6 / SE,358.3 / N,358.3 / N,358.3 / N,358.3 / N,171.6 / S,112.5 / ESE,60.0 / ENE,324.8 / NW,283.1 / WNW,337.5 / NNW,27.5 / NNE
4,2017-01-05,95.6 / E,56.3 / ENE,84.2 / E,65.3 / ENE,79.1 / E,101.4 / ESE,90.8 / E,90.8 / E,90.8 / E,90.8 / E,64.7 / ENE,95.6 / E,100.0 / E,78.2 / ENE,63.2 / ENE,84.4 / E,83.8 / E
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,2017-12-27,289.7 / WNW,337.5 / NNW,330.4 / NNW,349.2 / N,346.1 / NNW,14.4 / NNE,312.8 / NW,312.8 / NW,312.8 / NW,312.8 / NW,315.0 / NW,289.7 / WNW,30.0 / NNE,346.0 / NNW,317.0 / NW,120.9 / ESE,167.9 / SSE
361,2017-12-28,230.6 / SW,33.8 / NE,2.2 / N,180.5 / S,360.0 / N,235.0 / SW,73.6 / ENE,73.6 / ENE,73.6 / ENE,73.6 / ENE,39.4 / NE,230.6 / SW,60.0 / ENE,341.4 / NNW,323.5 / NW,30.9 / NNE,51.5 / NE
362,2017-12-29,154.7 / SSE,337.5 / NNW,317.8 / NW,337.2 / NNW,356.9 / N,279.5 / W,293.4 / WNW,293.4 / WNW,293.4 / WNW,293.4 / WNW,278.4 / W,154.7 / SSE,10.0 / N,332.0 / NNW,304.4 / NW,101.3 / ESE,61.2 / ENE
363,2017-12-30,331.9 / NNW,0.0 / N,341.9 / NNW,33.9 / NE,336.3 / NNW,301.0 / WNW,282.5 / WNW,282.5 / WNW,282.5 / WNW,282.5 / WNW,258.8 / W,331.9 / NNW,320.0 / NW,276.5 / W,322.6 / NW,109.7 / ESE,338.6 / NNW
364,2017-12-31,326.3 / NNW,317.8 / NW,327.9 / NNW,5.0 / N,335.9 / NNW,289.5 / WNW,280.8 / W,280.8 / W,280.8 / W,280.8 / W,270.0 / W,326.3 / NNW,350.0 / N,333.4 / NNW,298.7 / WNW,118.1 / ESE,60.6 / ENE

# 2017 최저기온

In [62]:
cold2017 = df1.loc[:"월.일",:"최저기온"]
cold2017.rename(columns={"최저기온":"강정동"}, inplace=True)
cold2017["건입동"] = df2[["최저기온"]]
cold2017["구좌"] = df3[["최저기온"]]
cold2017["남원읍"] = df4[["최저기온"]]
cold2017["대정읍"] = df5[["최저기온"]]
cold2017["색달동"] = df6[["최저기온"]]
cold2017["서귀동"] = df7[["최저기온"]]
cold2017["서호동"] = df8[["최저기온"]]
cold2017["성산"] = df9[["최저기온"]]
cold2017["아라동"] = df10[["최저기온"]]
cold2017["오등동"] = df11[["최저기온"]]
cold2017["외도일동"] = df12[["최저기온"]]
cold2017["용담"] = df13[["최저기온"]]
cold2017["우도"] = df14[["최저기온"]]
cold2017["월정"] = df15[["최저기온"]]
cold2017["표선읍"] = df16[["최저기온"]]
cold2017["한림읍"] = df17[["최저기온"]]

In [63]:
del cold2017["최대순간풍향"]
cold2017

,월.일,강정동,건입동,구좌,남원읍,대정읍,색달동,서귀동,서호동,성산,아라동,오등동,외도일동,용담,우도,월정,표선읍,한림읍
0,2017-01-01,3,6.0,5.6,4.6,3.5,4.3,0.5,0.5,0.5,0.5,2.0,3,5.0,8.8,6.7,3.7,4.3
1,2017-01-02,7.8,9.8,7.6,9.2,9.3,8.5,5.0,5.0,5.0,5.0,6.1,7.8,9.3,10.3,8.7,6.5,8.5
2,2017-01-03,5.9,6.9,5.1,5.2,6.8,4.6,1.0,1.0,1.0,1.0,1.6,5.9,5.0,7.7,5.9,4.8,4.3
3,2017-01-04,3,6.0,5.5,3.2,6.0,4.2,-0.1,-0.1,-0.1,-0.1,0.6,3,4.1,9.0,5.3,6.0,4.2
4,2017-01-05,7.5,8.4,7.6,7.9,8.7,8.1,2.2,2.2,2.2,2.2,3.8,7.5,7.8,10.1,9.1,6.7,7.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,2017-12-27,1.2,2.4,0.7,2.5,2.1,1.9,-3.3,-3.3,-3.3,-3.3,-2.2,1.2,2.1,2.9,3.1,0.4,1.0
361,2017-12-28,1.6,2.3,3.1,3.1,2.8,1.3,-3.1,-3.1,-3.1,-3.1,-2.2,1.6,1.6,3.8,3.8,0.5,1.3
362,2017-12-29,2.4,4.0,4.0,6.1,3.9,2.6,-0.9,-0.9,-0.9,-0.9,0.0,2.4,3.4,6.9,7.2,0.4,3.3
363,2017-12-30,4.6,9.5,7.8,7.2,7.3,6.8,4.6,4.6,4.6,4.6,6.4,4.6,9.1,8.6,8.5,5.5,8.5
364,2017-12-31,3.6,6.7,6.1,5.7,6.2,4.0,2.3,2.3,2.3,2.3,3.9,3.6,6.4,6.7,7.0,4.5,6.2

In [64]:
cold2017.to_excel("cold2017.xlsx")

# 2017 최고기온

In [65]:
hot2017 = df1.loc[:"월.일",:"최고기온"]
hot2017.rename(columns={"최고기온":"강정동"}, inplace=True)
hot2017["건입동"] = df2[["최고기온"]]
hot2017["구좌"] = df3[["최고기온"]]
hot2017["남원읍"] = df4[["최고기온"]]
hot2017["대정읍"] = df5[["최고기온"]]
hot2017["색달동"] = df6[["최고기온"]]
hot2017["서귀동"] = df7[["최고기온"]]
hot2017["서호동"] = df8[["최고기온"]]
hot2017["성산"] = df9[["최고기온"]]
hot2017["아라동"] = df10[["최고기온"]]
hot2017["오등동"] = df11[["최고기온"]]
hot2017["외도일동"] = df12[["최고기온"]]
hot2017["용담"] = df13[["최고기온"]]
hot2017["우도"] = df14[["최고기온"]]
hot2017["월정"] = df15[["최고기온"]]
hot2017["표선읍"] = df16[["최고기온"]]
hot2017["한림읍"] = df17[["최고기온"]]

In [66]:
del hot2017["최대순간풍향"]
del hot2017["최저기온"]
hot2017

,월.일,강정동,건입동,구좌,남원읍,대정읍,색달동,서귀동,서호동,성산,아라동,오등동,외도일동,용담,우도,월정,표선읍,한림읍
0,2017-01-01,14.4,13.0,12.3,13.9,13.7,12.5,10.4,10.4,10.4,10.4,10.8,14.4,11.8,13.2,13.6,14.3,12.3
1,2017-01-02,15,13.8,13.6,16.2,14.8,16.0,10.4,10.4,10.4,10.4,11.6,15,13.3,13.9,14.2,14.0,13.8
2,2017-01-03,15.7,11.7,10.6,16.4,12.0,15.2,9.4,9.4,9.4,9.4,9.6,15.7,10.9,11.2,11.8,13.4,10.7
3,2017-01-04,15.7,12.2,11.6,16.8,14.4,16.0,9.8,9.8,9.8,9.8,10.1,15.7,11.2,11.9,12.1,12.7,12.2
4,2017-01-05,14.3,13.5,14.1,15.3,15.4,14.7,10.8,10.8,10.8,10.8,12.0,14.3,13.4,14.5,14.4,14.7,14.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,2017-12-27,7.8,5.9,4.7,8.7,5.7,8.1,2.7,2.7,2.7,2.7,3.1,7.8,4.7,5.2,5.0,5.2,4.9
361,2017-12-28,10.1,7.2,6.9,10.7,8.5,9.9,4.5,4.5,4.5,4.5,5.4,10.1,6.8,7.4,8.2,7.2,7.0
362,2017-12-29,12.7,11.7,11.2,13.4,11.8,13.6,8.9,8.9,8.9,8.9,10.1,12.7,11.1,11.8,11.6,11.8,11.1
363,2017-12-30,13.5,12.5,11.1,14.1,13.3,13.2,11.0,11.0,11.0,11.0,10.6,13.5,11.6,11.8,12.0,12.0,12.4
364,2017-12-31,8.9,9.8,8.8,11.1,9.9,8.8,6.1,6.1,6.1,6.1,7.5,8.9,9.6,9.9,10.1,9.1,9.1

In [67]:
hot2017.to_excel("hot2017.xlsx")

# 2017 강우량

In [68]:
rain2017 = df1.loc[:"월.일",:"일강우량"]
rain2017.rename(columns={"일강우량":"강정동"}, inplace=True)
rain2017["건입동"] = df2[["일강우량"]]
rain2017["구좌"] = df3[["일강우량"]]
rain2017["남원읍"] = df4[["일강우량"]]
rain2017["대정읍"] = df5[["일강우량"]]
rain2017["색달동"] = df6[["일강우량"]]
rain2017["서귀동"] = df7[["일강우량"]]
rain2017["서호동"] = df8[["일강우량"]]
rain2017["성산"] = df9[["일강우량"]]
rain2017["아라동"] = df10[["일강우량"]]
rain2017["오등동"] = df11[["일강우량"]]
rain2017["외도일동"] = df12[["일강우량"]]
rain2017["용담"] = df13[["일강우량"]]
rain2017["우도"] = df14[["일강우량"]]
rain2017["월정"] = df15[["일강우량"]]
rain2017["표선읍"] = df16[["일강우량"]]
rain2017["한림읍"] = df17[["일강우량"]]

In [69]:
del rain2017["최대순간풍향"]
del rain2017["최저기온"]
del rain2017['최고기온']
rain2017

,월.일,강정동,건입동,구좌,남원읍,대정읍,색달동,서귀동,서호동,성산,아라동,오등동,외도일동,용담,우도,월정,표선읍,한림읍
0,2017-01-01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2017-01-02,0.0,0.9,0.5,0.5,0.0,0.0,0.5,0.5,0.5,0.5,0.5,0.0,0.5,0.5,0.0,0.0,0.5
2,2017-01-03,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2017-01-04,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2017-01-05,0.0,9.8,6.5,19.5,0.5,0.5,7.0,7.0,7.0,7.0,4.0,0.0,5.0,8.0,6.0,20.5,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,2017-12-27,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
361,2017-12-28,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
362,2017-12-29,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
363,2017-12-30,1.0,1.4,0.0,0.0,4.5,2.0,3.0,3.0,3.0,3.0,4.5,1.0,1.0,0.0,0.5,0.0,1.5
364,2017-12-31,0.0,1.5,1.0,0.0,0.5,0.5,7.0,7.0,7.0,7.0,5.0,0.0,1.5,0.5,3.0,0.0,0.0

In [70]:
rain2017.to_excel("rain2017.xlsx")

In [90]:
# =wind2017.loc[:,"강정동":"한림읍"]
# reg = "+"

,강정동,건입동,구좌,남원읍,대정읍,색달동,서귀동,서호동,성산,아라동,오등동,외도일동,용담,우도,월정,표선읍,한림읍
0,163.1 / SSE,45.0 / NE,325.6 / NW,353.1 / N,143.7 / SE,20.5 / NNE,19.3 / NNE,19.3 / NNE,19.3 / NNE,19.3 / NNE,143.4 / SE,163.1 / SSE,80.0 / E,316.1 / NW,316.1 / NW,316.1 / NW,316.1 / NW
1,115.3 / ESE,317.8 / NW,312.5 / NW,3.0 / N,243.3 / WSW,330.2 / NNW,173.1 / S,173.1 / S,173.1 / S,173.1 / S,165.9 / SSE,115.3 / ESE,180.0 / S,328.2 / NNW,328.2 / NNW,328.2 / NNW,328.2 / NNW
2,135.0 / SE,298.1 / WNW,312.0 / NW,188.0 / S,345.8 / NNW,329.1 / NNW,314.6 / NW,314.6 / NW,314.6 / NW,314.6 / NW,171.6 / S,135.0 / SE,320.0 / NW,317.6 / NW,317.6 / NW,317.6 / NW,317.6 / NW
3,112.5 / ESE,39.4 / NE,301.3 / WNW,342.8 / NNW,63.6 / ENE,142.6 / SE,358.3 / N,358.3 / N,358.3 / N,358.3 / N,171.6 / S,112.5 / ESE,60.0 / ENE,324.8 / NW,324.8 / NW,324.8 / NW,324.8 / NW
4,95.6 / E,56.3 / ENE,84.2 / E,65.3 / ENE,79.1 / E,101.4 / ESE,90.8 / E,90.8 / E,90.8 / E,90.8 / E,64.7 / ENE,95.6 / E,100.0 / E,78.2 / ENE,78.2 / ENE,78.2 / ENE,78.2 / ENE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,289.7 / WNW,337.5 / NNW,330.4 / NNW,349.2 / N,346.1 / NNW,14.4 / NNE,312.8 / NW,312.8 / NW,312.8 / NW,312.8 / NW,315.0 / NW,289.7 / WNW,30.0 / NNE,346.0 / NNW,346.0 / NNW,346.0 / NNW,346.0 / NNW
361,230.6 / SW,33.8 / NE,2.2 / N,180.5 / S,360.0 / N,235.0 / SW,73.6 / ENE,73.6 / ENE,73.6 / ENE,73.6 / ENE,39.4 / NE,230.6 / SW,60.0 / ENE,341.4 / NNW,341.4 / NNW,341.4 / NNW,341.4 / NNW
362,154.7 / SSE,337.5 / NNW,317.8 / NW,337.2 / NNW,356.9 / N,279.5 / W,293.4 / WNW,293.4 / WNW,293.4 / WNW,293.4 / WNW,278.4 / W,154.7 / SSE,10.0 / N,332.0 / NNW,332.0 / NNW,332.0 / NNW,332.0 / NNW
363,331.9 / NNW,0.0 / N,341.9 / NNW,33.9 / NE,336.3 / NNW,301.0 / WNW,282.5 / WNW,282.5 / WNW,282.5 / WNW,282.5 / WNW,258.8 / W,331.9 / NNW,320.0 / NW,276.5 / W,276.5 / W,276.5 / W,276.5 / W
364,326.3 / NNW,317.8 / NW,327.9 / NNW,5.0 / N,335.9 / NNW,289.5 / WNW,280.8 / W,280.8 / W,280.8 / W,280.8 / W,270.0 / W,326.3 / NNW,350.0 / N,333.4 / NNW,333.4 / NNW,333.4 / NNW,333.4 / NNW